    name: "minSalePriceGreaterThanZero"
    type: "double_strict"
    field: "minSalePrice"
    comparator: "less_than_or_equal"
    compared: "0"
---
    name: "minSalePrice greater than min listprice"
    type: "double_within"
    field: "minSalePrice"
    comparator: "great_than"
    compared: "minListPrice"
---
    name: "storeid greater than 1"
    type: "double_strict"
    field: "storeId"
    comparator: "less_than"
    compared: 1
