    name: "minSalePriceGreaterThanZero"
    type: "double_strict"
    field: "minSalePrice"
    comparator: "less_than_or_equal"
    compared: "0"
    notifications :
     - slack
     - sms
    isAgg: false
    aggType: ""
---
    name: "Aggregatation based on the count for minSalePrice"
    type: "double_strict"
    field: "storeId"
    comparator: "less_than_or_equal"
    compared: 0
    notifications :
     - slack
     - sms
    isAgg: true
    aggType: "count"
    limit: 3