    name: "minSalePriceGreaterThanZero"
    type: "double_strict"
    field: "minSalePrice"
    comparator: "less_than_or_equal"
    compared: "0"
    notifications :
     - slack
     - sms
    isAgg: false
    aggType: ""