    name: "minSalePriceGreaterThanZero"
    type: "double_strict"
    field: "minSalePrice"
    comparator: "less_than_or_equal"
    compared: "0"
    notification : "slack"
    isAgg: false
    aggType: ""